#!/bin/bash
exec 2>&1
# You need to be in the /workspace directory to find the VLLM shared libraries
cd /workspace
exec python3 -m vllm.entrypoints.openai.api_server --model $AZUREML_MODEL_DIR/$MODEL_PATH $VLLM_ARGS
