# If deploying on older V100 you need to use an older version of VLLM as latest pytorch does not support the HW
FROM vllm/vllm-openai:v0.2.7

RUN apt-get update && \
    apt-get install -y --no-install-recommends runit
ENV MODEL_PATH /models/SmolLM2-135M-hf

ADD runit_folder/api_server /var/runit/api_server
RUN sed -i 's/\r$//g' /var/runit/api_server/run
RUN chmod +x /var/runit/api_server/run
ENV SVDIR=/var/runit
ENV WORKER_TIMEOUT=3600
EXPOSE 5001
ENTRYPOINT [ "runsvdir", "/var/runit" ]
